import {
  WAIST,
  INSEAM,
  GLOVE,
  HAT,
  CHEST,
  NECK,
  SLEEVE,
  COATLENGTH,
  SHIRT,
  SHOESMEN,
  SHOESWOMEN,
  DRESSORPANT,
  CUP,
  BUST,
  UNDERBUST,
  HIPS,
} from '@packages/backend/convex/validators/sizing';

import { SizingMetricConfig } from '~/types/sizing';

export const sizingMetrics: Record = {
  // General metrics
  waist: {
    section: 'general',
    field: 'waist',
    label: 'Waist',
    values: WAIST,
    unit: 'inches',
    pickerType: 'numeric',
  },
  inseam: {
    section: 'general',
    field: 'inseam',
    label: 'Inseam',
    values: INSEAM,
    unit: 'inches',
    pickerType: 'numeric',
  },
  glove: {
    section: 'general',
    field: 'glove',
    label: 'Glove',
    values: GLOVE,
    pickerType: 'numeric',
  },
  hat: {
    section: 'general',
    field: 'hat',
    label: 'Hat',
    values: HAT,
    pickerType: 'numeric',
  },

  // Male metrics
  chest: {
    section: 'male',
    field: 'chest',
    label: 'Chest',
    values: CHEST,
    unit: 'inches',
    pickerType: 'numeric',
  },
  neck: {
    section: 'male',
    field: 'neck',
    label: 'Neck',
    values: NECK,
    unit: 'inches',
    pickerType: 'numeric',
  },
  sleeve: {
    section: 'male',
    field: 'sleeve',
    label: 'Sleeve',
    values: SLEEVE,
    unit: 'inches',
    pickerType: 'numeric',
  },
  maleShirt: {
    section: 'male',
    field: 'shirt',
    label: 'T-Shirt',
    values: SHIRT,
    pickerType: 'size',
  },
  maleShoes: {
    section: 'male',
    field: 'shoes',
    label: 'Shoe',
    values: SHOESMEN,
    pickerType: 'numeric',
  },
  maleCoatLength: {
    section: 'male',
    field: 'coatLength',
    label: 'Jacket',
    values: COATLENGTH,
    pickerType: 'enum',
  },

  // Female metrics
  dress: {
    section: 'female',
    field: 'dress',
    label: 'Dress',
    values: DRESSORPANT,
    pickerType: 'numeric',
  },
  bust: {
    section: 'female',
    field: 'bust',
    label: 'Bust',
    values: BUST,
    unit: 'inches',
    pickerType: 'numeric',
  },
  underbust: {
    section: 'female',
    field: 'underbust',
    label: 'Under Bust',
    values: UNDERBUST,
    unit: 'inches',
    pickerType: 'numeric',
  },
  cup: {
    section: 'female',
    field: 'cup',
    label: 'Cup',
    values: CUP,
    pickerType: 'size',
  },
  hip: {
    section: 'female',
    field: 'hips',
    label: 'Hip',
    values: HIPS,
    unit: 'inches',
    pickerType: 'numeric',
  },
  femaleShirt: {
    section: 'female',
    field: 'shirt',
    label: 'T-Shirt',
    values: SHIRT,
    pickerType: 'size',
  },
  pants: {
    section: 'female',
    field: 'pants',
    label: 'Pants',
    values: DRESSORPANT,
    pickerType: 'numeric',
  },
  femaleShoes: {
    section: 'female',
    field: 'shoes',
    label: 'Shoe',
    values: SHOESWOMEN,
    pickerType: 'numeric',
  },
  femaleCoatLength: {
    section: 'female',
    field: 'coatLength',
    label: 'Jacket',
    values: COATLENGTH,
    pickerType: 'enum',
  },
};
