name: Development Build

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  fingerprint:
    type: fingerprint

  get_ios_build:
    type: get-build
    needs: [fingerprint]
    params:
      platform: ios
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: development

  build_ios:
    type: build
    needs: [get_ios_build]
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    params:
      platform: ios
      profile: development

  publish_update:
    type: update
    needs: [get_ios_build]
    if: ${{ needs.get_ios_build.outputs.build_id }}
    params:
      branch: development
      platform: ios
