name: Development Update
on:
  push:
    branches:
      - 'chore/**'
      - 'feat/**'
      - 'fix/**'
jobs:
  update_ios:
    type: update
    params:
      platform: ios
      channel: development
