import { z } from 'zod'

// Re-export sizing constants and validators from sizing.ts
export {
  WAIST,
  INSEAM,
  GLOVE,
  HAT,
  CHEST,
  NECK,
  SLEEVE,
  COATLENGTH,
  SHIRT,
  SHOESMEN,
  SHOESWOMEN,
  SHOEWIDTH,
  DRESSORPANT,
  CUP,
  BUST,
  UNDERBUST,
  HIPS,
  zWaist,
  zInseam,
  zGlove,
  zHat,
  zChest,
  zNeck,
  zSleeve,
  zCoatLength,
  zShirt,
  zShoesMen,
  zShoesWomen,
  zShoeWidth,
  zDressOrPant,
  zCup,
  zBust,
  zUnderBust,
  zHips
} from '../sizing'

/**
 * Sizing object schema
 * Comprehensive clothing measurements for dancers
 */
export const sizingObject = z.object({
  general: z
    .object({
      waist: z
        .enum([
          '20',
          '21',
          '22',
          '23',
          '24',
          '25',
          '26',
          '27',
          '28',
          '29',
          '30',
          '31',
          '32',
          '33',
          '34',
          '35',
          '36',
          '38',
          '40',
          '42',
          '44',
          '46',
          '48',
          '50',
          '52',
          '54',
          '56',
          '58',
          '60',
          '62',
          '64',
          '66',
          '68',
          '70'
        ])
        .optional(),
      inseam: z
        .enum([
          '26',
          '27',
          '28',
          '29',
          '30',
          '31',
          '32',
          '33',
          '34',
          '35',
          '36'
        ])
        .optional(),
      glove: z
        .enum([
          '6',
          '6.5',
          '7',
          '7.5',
          '8',
          '8.5',
          '9',
          '9.5',
          '10',
          '10.5',
          '11',
          '11.5',
          '12'
        ])
        .optional(),
      hat: z.enum(['19', '20', '21', '22', '23', '24', '25']).optional()
    })
    .partial()
    .optional(),

  male: z
    .object({
      neck: z
        .enum([
          '14',
          '14.5',
          '15',
          '15.5',
          '16',
          '16.5',
          '17',
          '17.5',
          '18',
          '18.5',
          '19',
          '19.5',
          '20',
          '20.5',
          '21',
          '21.5',
          '22',
          '22.5',
          '23',
          '23.5',
          '24',
          '24.5',
          '25',
          '25.5',
          '26',
          '26.5',
          '27',
          '27.5',
          '28',
          '28.5',
          '29',
          '29.5',
          '30'
        ])
        .optional(),
      chest: z
        .enum([
          '24',
          '25',
          '26',
          '27',
          '28',
          '29',
          '30',
          '31',
          '32',
          '33',
          '34',
          '35',
          '36',
          '37',
          '38',
          '39',
          '40',
          '41',
          '42',
          '43',
          '44',
          '45',
          '46',
          '47',
          '48',
          '49',
          '50',
          '51',
          '52',
          '53',
          '54',
          '55',
          '56',
          '57',
          '58',
          '59',
          '60',
          '61',
          '62',
          '63'
        ])
        .optional(),
      sleeve: z
        .enum([
          '15',
          '15.5',
          '16',
          '16.5',
          '17',
          '17.5',
          '18',
          '18.5',
          '19',
          '19.5',
          '20',
          '20.5',
          '21',
          '21.5',
          '22',
          '22.5',
          '23',
          '23.5',
          '24',
          '24.5',
          '25',
          '25.5',
          '26',
          '26.5',
          '27',
          '27.5',
          '28',
          '28.5',
          '29',
          '29.5',
          '30',
          '30.5',
          '31',
          '31.5',
          '32',
          '32.5',
          '33',
          '33.5',
          '34',
          '34.5',
          '35',
          '35.5',
          '36',
          '36.5',
          '37',
          '37.5',
          '38',
          '38.5',
          '39',
          '39.5',
          '40'
        ])
        .optional(),
      coatLength: z.enum(['Short', 'Regular', 'Long', 'Extra-Long']).optional(),
      shirt: z
        .enum(['XXS', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'])
        .optional(),
      shoes: z
        .enum([
          '6',
          '6.5',
          '7',
          '7.5',
          '8',
          '8.5',
          '9',
          '9.5',
          '10',
          '10.5',
          '11',
          '11.5',
          '12',
          '12.5',
          '13',
          '13.5',
          '14',
          '14.5',
          '15',
          '15.5',
          '16',
          '16.5',
          '17',
          '17.5'
        ])
        .optional()
    })
    .partial()
    .optional(),

  female: z
    .object({
      hips: z
        .enum([
          '15',
          '16',
          '17',
          '18',
          '19',
          '20',
          '21',
          '22',
          '23',
          '24',
          '25',
          '26',
          '27',
          '28',
          '29',
          '30',
          '31',
          '32',
          '33',
          '34',
          '35',
          '36',
          '38',
          '40',
          '42',
          '44',
          '46',
          '48',
          '50',
          '52',
          '54',
          '56',
          '58',
          '60',
          '62',
          '64',
          '66',
          '68',
          '70'
        ])
        .optional(),
      bust: z
        .enum([
          '19',
          '20',
          '21',
          '22',
          '23',
          '24',
          '25',
          '26',
          '27',
          '28',
          '29',
          '30',
          '31',
          '32',
          '33',
          '34',
          '35',
          '36',
          '38',
          '40',
          '42',
          '44',
          '46',
          '48',
          '50',
          '52',
          '54',
          '56',
          '58',
          '60',
          '62',
          '64',
          '66'
        ])
        .optional(),
      underbust: z
        .enum([
          '19',
          '20',
          '21',
          '22',
          '23',
          '24',
          '25',
          '26',
          '27',
          '28',
          '29',
          '30',
          '31',
          '32',
          '33',
          '34',
          '35',
          '36',
          '38',
          '40',
          '42',
          '44',
          '46',
          '48',
          '50',
          '52',
          '54',
          '56',
          '58',
          '60',
          '62',
          '64',
          '66'
        ])
        .optional(),
      cup: z
        .enum([
          'AA',
          'A',
          'B',
          'C',
          'D',
          'DD/E',
          'DDD/F',
          'DDDD/G',
          'H',
          'I',
          'J',
          'K'
        ])
        .optional(),
      coatLength: z.enum(['Short', 'Regular', 'Long', 'Extra-Long']).optional(),
      shirt: z
        .enum(['XXS', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'])
        .optional(),
      dress: z
        .enum([
          '00',
          '0',
          '2',
          '4',
          '6',
          '8',
          '10',
          '12',
          '14',
          '16',
          '18',
          '20',
          '22',
          '24',
          '26',
          '28',
          '30'
        ])
        .optional(),
      pants: z
        .enum([
          '00',
          '0',
          '2',
          '4',
          '6',
          '8',
          '10',
          '12',
          '14',
          '16',
          '18',
          '20',
          '22',
          '24',
          '26',
          '28',
          '30'
        ])
        .optional(),
      shoes: z
        .enum([
          '4',
          '4.5',
          '5',
          '5.5',
          '6',
          '6.5',
          '7',
          '7.5',
          '8',
          '8.5',
          '9',
          '9.5',
          '10',
          '10.5',
          '11',
          '11.5',
          '12',
          '12.5',
          '13',
          '13.5',
          '14',
          '14.5',
          '15',
          '15.5',
          '16',
          '16.5',
          '17'
        ])
        .optional()
    })
    .partial()
    .optional()
})

/**
 * Form schema for sizing
 * Validates sizing information
 */
export const sizingFormSchema = z.object({
  sizing: sizingObject.optional()
})

/**
 * Database field for sizing
 * Optional sizing object
 */
export const sizingDbField = sizingObject.optional()

export type SizingFormValues = z.infer<typeof sizingFormSchema>
